# Welcome to Jekyll!
#

# Site settings
title: Fan Bai
description: |
  The web page of Dr. Fan Bai,
  Ph.D in the Department of
  Maths, Florida State University
owner: Fan Bai
first_published: 2022
email:  baifanhorst@gmail.com
baseurl: ""
# url: "http://localhost:4000"
permalink: pretty
collections:
  publications:
