# Welcome to Jekyll!
#

# Site settings
title: SESE
description: |
  The web page of Dr. SeSe,
  Ph.D in the Department of
  Statistics, Florida State University
owner: SESE
first_published: 2015
email: seungchoi1850@gmail.com
baseurl: ""
# url: "http://localhost:4000"
permalink: pretty
collections:
  publications:
