# Welcome to Jekyll!
#

# Site settings
title: SeSe
description: |
  The web page of Dr. SeSe,
  Assistant Professor in the Department of
  Statistics, Florida State University
owner: SeSe
first_published: 2015
email: seungchoi1850@gmail.com
baseurl: "https://github.com/YinpuLiPIPI"
# url: "http://localhost:4000"
permalink: pretty
collections:
  publications:
